config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :chats do
    member do
      post 'criar_mensagem'
    end
  end
  root to: "pages#home"

end

app/models/chat.rb
class Chat < ActiveRecord::Base
	has_many :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :chat
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy, :criar_mensagem]
  before_filter :authenticate_user!

  # GET /chats
  # GET /chats.json
  def index
    @chats = Chat.all
  end

  # GET /chats/1
  # GET /chats/1.json
  def show
    @new_message = Message.new(chat: @chat)
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats
  # POST /chats.json
  def create
    @chat = Chat.new(chat_params)

    respond_to do |format|
      if @chat.save
        format.html { redirect_to @chat, notice: 'Chat was successfully created.' }
        format.json { render :show, status: :created, location: @chat }
      else
        format.html { render :new }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1
  # PATCH/PUT /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to @chat, notice: 'Chat was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1
  # DELETE /chats/1.json
  def destroy
    @chat.destroy
    respond_to do |format|
      format.html { redirect_to chats_url, notice: 'Chat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def criar_mensagem
    p = params.require(:message).permit(:chat_id, :from, :body)
    @message = @chat.messages.create(p)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_params
      params.require(:chat).permit(:session_name, :ativo)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if params[:id] && template_exists?(params[:id], ["pages"])
      render params[:id]
    else
      redirect_to '/404.html', :status => 404
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def broadcast(channel, &block)
		message = {channel: channel, data: capture(&block)}
		uri = URI.parse("http://localhost:9292/faye")
		Net::HTTP.post_form(uri, message: message.to_json)
	end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_form.html.erb
<%= form_for(@chat) do |f| %>
  <% if @chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
      <% @chat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :session_name %><br>
    <%= f.text_field :session_name %>
  </div>
  <div class="field">
    <%= f.label :ativo %><br>
    <%= f.check_box :ativo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chats/_message.html.erb
<div class="message">
	<%= message.from %>: 
	<%= message.body.to_s.gsub("\n", "<br/>").html_safe %>
</div>

app/views/chats/criar_mensagem.js.erb
<% broadcast "/chats/chat_#{@chat.id}" do %>
	var content = "<%= escape_javascript(render partial: 'message', locals: {message: @message}) %>";
	$("#message_list").append(content);
	$("#message_body").val("");
	$("#message_body").focus();
<% end %>

app/views/chats/edit.html.erb
<h1>Editing Chat</h1>

<%= render 'form' %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<p id="notice"><%= notice %></p>

<%= current_user.email %>
<%= link_to 'Logout', destroy_user_session_path, { :class => 'signout', :method => :delete} %>

<h1>Listing Chats</h1>

<table>
  <thead>
    <tr>
      <th>Session name</th>
      <th>Ativo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chats.each do |chat| %>
      <tr>
        <td><%= chat.session_name %></td>
        <td><%= chat.ativo %></td>
        <td><%= link_to 'Show', chat %></td>
        <td><%= link_to 'Edit', edit_chat_path(chat) %></td>
        <td><%= link_to 'Destroy', chat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chat', new_chat_path %>

app/views/chats/new.html.erb
<h1>New Chat</h1>

<%= render 'form' %>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<!doctype html> 
<html lang="en"> 
<head> 
	<meta charset="UTF-8" />
	<title>Phaser - Making your first game, part 1</title>
	<script type="text/javascript" src="js/phaser.min.js"></script>
    <style type="text/css">
        body {
            margin: 0;
        }
    </style>
</head>

<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_chat_path(@chat) %> |
<%= link_to 'Back', chats_path %>
<p>
  <strong>Session name:</strong>
  <%= @chat.session_name %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @chat.ativo %>
</p>

<h2>Messages</h2>
<div id="message_list">
	<% @chat.messages.each do |mess| %>
		<%= render partial: 'message', locals: {message: mess} %>
	<% end -%>
</div>
<%= form_for @new_message, url: criar_mensagem_chat_path(@chat), remote: true do |f| %>
	From: <%= f.text_field :from %><br/>
	Body: <%= f.text_area :body %><br/>
	<%= f.submit %>
<% end -%>

<button onClick="enviar()">teste enviar</button>
<button onClick="andar()">Pular</button>

<script type="text/javascript">
var faye = null;
function enviar() {
	faye.publish("/chats/chat_<%= @chat.id %>", {'data': 'andar'});
}
function chegou_mensagem(data) {
	eval(data);
}

$(function() {
	faye = connect_to_faye();
	
	 // connect_to_faye() faz isso: new Faye.Client("http://localhost:9292/faye");
	faye.subscribe("/chats/chat_<%= @chat.id %>", chegou_mensagem);
	
});



var game = new Phaser.Game(800, 600, Phaser.AUTO, '', { preload: preload, create: create, update: update });

function preload() {
	game.load.image ('sky', "#{asset_url('sky.png')");
	game.load.image ('ground', 'assets/images/platform.png');
	game.load.image ('star', 'assets/images/star.png');
	game.load.spritesheet ('dude', 'assets/images/dude.png', 32, 48);
}

var platforms;
var cursors;
var player;

function create() {
	game.physics.startSystem(Phaser.Physics.ARCADE);
	game.add.sprite(0, 0, 'sky');
	
	platforms = game.add.group();
	platforms.enableBody = true;
	
	var ground = platforms.create(0, game.world.height - 64, 'ground');
	ground.scale.setTo(2, 2);
	ground.body.immovable = true;
	
	var ledge = platforms.create(400, 400, 'ground');
	ledge.body.immovable = true;
	ledge = platforms.create(-150, 250, 'ground');
	ledge.body.immovable = true;
	
	player = game.add.sprite(32, game.world.height - 150, 'dude');
	game.physics.arcade.enable(player);
	player.body.bounce.y = 0.2;
	player.body.gravity.y = 300;
	player.body.collideWorldBounds = true;

	player.animations.add('left', [0, 1, 2, 3], 10, true);
	player.animations.add('right', [5, 6, 7, 8], 10, true);

	cursors = game.input.keyboard.createCursorKeys();

}

function update() {

	game.physics.arcade.collide(player, platforms);

	player.body.velocity.x = 0;

	/*if (cursors.left.isDown) {
        //  Move to the left
        player.body.velocity.x = -150;

        player.animations.play('left');
    }
    else if (cursors.right.isDown) {
        //  Move to the right
        player.body.velocity.x = 150;

        player.animations.play('right');
    }
    else {
        //  Stand still
        player.animations.stop();

        player.frame = 4;
    }*/

	if (cursors.up.isDown && player.body.touching.down) {
		player.body.velocity.y = -350;
	}
}

function andar(){

	player.body.velocity.y = -100;

}

</script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chattest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'http://localhost:9292/faye.js' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en" class="app">
  <head>
    <meta charset="utf-8" />
    <title>Yeeeha</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  </head>
  <body class="">
	<%= link_to 'Chat', chats_path %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>